# Generated by Django 2.0.7 on 2018-07-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='日期')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('autor', models.CharField(max_length=20, verbose_name='作者')),
                ('banner', models.ImageField(upload_to='', verbose_name='图片')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='日期')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('passward', models.CharField(max_length=8, verbose_name='密码')),
                ('othername', models.CharField(max_length=30, verbose_name='昵称')),
                ('tel', models.CharField(max_length=8, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('introduce', models.CharField(max_length=200, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
